//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prbd_1819_g04.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prbd_1819_g04.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;/Pictures/Title.jpg&quot;.
        /// </summary>
        public static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à does exist.
        /// </summary>
        public static string Error_DoesExist {
            get {
                return ResourceManager.GetString("Error_DoesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à does not exist.
        /// </summary>
        public static string Error_DoesNotExist {
            get {
                return ResourceManager.GetString("Error_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Email.
        /// </summary>
        public static string Error_InvalidEmail {
            get {
                return ResourceManager.GetString("Error_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &gt;= 3.
        /// </summary>
        public static string Error_LengthGreaterEqual3 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &gt;= 8.
        /// </summary>
        public static string Error_LengthGreaterEqual8 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à must match confirm password.
        /// </summary>
        public static string Error_MustMatchConfirmPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à must match password.
        /// </summary>
        public static string Error_MustMatchPassword {
            get {
                return ResourceManager.GetString("Error_MustMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à not available.
        /// </summary>
        public static string Error_NotAvailable {
            get {
                return ResourceManager.GetString("Error_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à required.
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wrong password.
        /// </summary>
        public static string Error_WrongPassword {
            get {
                return ResourceManager.GetString("Error_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string LoginView_Cancel {
            get {
                return ResourceManager.GetString("LoginView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à THE BIBLIOPRALINE.
        /// </summary>
        public static string LoginView_Message_0 {
            get {
                return ResourceManager.GetString("LoginView_Message_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If your don&apos;t have a login and a password, click.
        /// </summary>
        public static string LoginView_Message_1 {
            get {
                return ResourceManager.GetString("LoginView_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à here.
        /// </summary>
        public static string LoginView_Message_2 {
            get {
                return ResourceManager.GetString("LoginView_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to sign-up..
        /// </summary>
        public static string LoginView_Message_3 {
            get {
                return ResourceManager.GetString("LoginView_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password:.
        /// </summary>
        public static string LoginView_Password {
            get {
                return ResourceManager.GetString("LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string LoginView_Title {
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username:.
        /// </summary>
        public static string LoginView_Username {
            get {
                return ResourceManager.GetString("LoginView_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date of birth.
        /// </summary>
        public static string SignupView_Date {
            get {
                return ResourceManager.GetString("SignupView_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email (ceci est votre identifiant)(*).
        /// </summary>
        public static string SignupView_Email {
            get {
                return ResourceManager.GetString("SignupView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name(ceci est votre identifiant)(*).
        /// </summary>
        public static string SignupView_Nom {
            get {
                return ResourceManager.GetString("SignupView_Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string SignupView_Password {
            get {
                return ResourceManager.GetString("SignupView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password_Confirm.
        /// </summary>
        public static string SignupView_PasswordConfirm {
            get {
                return ResourceManager.GetString("SignupView_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à secondName(*).
        /// </summary>
        public static string SignupView_Prenom {
            get {
                return ResourceManager.GetString("SignupView_Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Role(*).
        /// </summary>
        public static string SignupView_Role {
            get {
                return ResourceManager.GetString("SignupView_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register.
        /// </summary>
        public static string SignupView_Title {
            get {
                return ResourceManager.GetString("SignupView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save yourself in our database.
        /// </summary>
        public static string SignupView_Title1 {
            get {
                return ResourceManager.GetString("SignupView_Title1", resourceCulture);
            }
        }
    }
}
